import { isClaimPath } from "./claims.mjs";
import { exactKeys, object, safeIdentifier, sha, sha256, timestamp } from "./validation.mjs";

export const GROUPED_AUTHORIZATION_ACTIONS = ["commit_candidate", "push_branch", "create_draft_pull_request"];
export const REQUIRED_ACTION_CHECKS = Object.freeze({ commit_candidate: ["local_quality", "activation_unchanged"], push_branch: ["committed_diff_policy", "local_quality", "activation_unchanged"], create_draft_pull_request: ["remote_branch_matches_commit"] });
export const BUNDLE_KEYS = ["authorizationId", "candidate", "expiresAt", "humanDecision", "issuedAt", "repositoryIdentity", "schemaVersion", "steps"];
const NEXT_DYNAMIC_SEGMENT = /^(?:\[[A-Za-z_][A-Za-z0-9_]*\]|\[\.\.\.[A-Za-z_][A-Za-z0-9_]*\]|\[\[\.\.\.[A-Za-z_][A-Za-z0-9_]*\]\])(?:\.[A-Za-z0-9._-]+)?$/;

export function nonEmptyText(value, label, maximum) { if (typeof value !== "string" || !value.trim() || value !== value.trim() || value.length > maximum) throw new Error(`${label} must be trimmed non-empty text of at most ${maximum} characters`); return value; }
function sameArray(left, right) { return left.length === right.length && left.every((item, index) => item === right[index]); }
function exactAuthorizationPath(path) { return isClaimPath(path) && !/[*?{}]/.test(path) && path.split("/").every((segment) => !/[\[\]]/.test(segment) || NEXT_DYNAMIC_SEGMENT.test(segment)); }
export function validateDecision(raw, label = "humanDecision") { const decision = object(raw, label); exactKeys(decision, label, ["decisionId", "source", "statement"]); safeIdentifier(decision.decisionId, `${label}.decisionId`); nonEmptyText(decision.source, `${label}.source`, 512); nonEmptyText(decision.statement, `${label}.statement`, 2000); return decision; }

export function validateAuthorizationBundle(raw, policy) {
  const config = object(policy?.groupedAuthorizations, "policy.groupedAuthorizations"); if (config.enabled !== true) throw new Error("grouped authorizations are disabled by policy"); if (policy.mode !== "active") throw new Error("grouped authorizations require active policy mode");
  const bundle = object(raw, "authorization"); exactKeys(bundle, "authorization", BUNDLE_KEYS); if (bundle.schemaVersion !== 1) throw new Error("authorization.schemaVersion must be 1"); safeIdentifier(bundle.authorizationId, "authorization.authorizationId"); nonEmptyText(bundle.repositoryIdentity, "authorization.repositoryIdentity", 512); validateDecision(bundle.humanDecision); timestamp(bundle.issuedAt, "authorization.issuedAt"); timestamp(bundle.expiresAt, "authorization.expiresAt");
  if (Date.parse(bundle.expiresAt) - Date.parse(bundle.issuedAt) <= 0 || Date.parse(bundle.expiresAt) - Date.parse(bundle.issuedAt) > config.maxLifetimeSeconds * 1000) throw new Error("authorization lifetime exceeds the governed limit");
  const candidate = object(bundle.candidate, "authorization.candidate"); exactKeys(candidate, "authorization.candidate", ["activationDigest", "allowedPaths", "baseSha", "branch", "candidateId", "commitSha"]); safeIdentifier(candidate.candidateId, "candidate.candidateId"); sha(candidate.baseSha, "candidate.baseSha"); if (typeof candidate.branch !== "string" || !/^codex\/[A-Za-z0-9][A-Za-z0-9._/-]{0,120}$/.test(candidate.branch) || candidate.branch.includes("..") || candidate.branch.endsWith("/")) throw new Error("candidate.branch must be one safe codex/ branch"); if (candidate.branch === policy.reconciliation.defaultBranch) throw new Error("candidate.branch cannot be the default branch"); if (candidate.commitSha !== null) sha(candidate.commitSha, "candidate.commitSha"); sha256(candidate.activationDigest, "candidate.activationDigest");
  if (!Array.isArray(candidate.allowedPaths) || !candidate.allowedPaths.length || candidate.allowedPaths.length > (config.maxChangedFiles ?? policy.limits.maxChangedFiles) || candidate.allowedPaths.some((path) => !exactAuthorizationPath(path)) || new Set(candidate.allowedPaths).size !== candidate.allowedPaths.length) throw new Error("candidate.allowedPaths must contain unique canonical repository paths"); if (!sameArray(candidate.allowedPaths, [...candidate.allowedPaths].sort())) throw new Error("candidate.allowedPaths must be sorted");
  if (!Array.isArray(bundle.steps) || !bundle.steps.length || bundle.steps.length > config.maxSteps) throw new Error("authorization.steps exceeds the governed sequence length"); const actions = bundle.steps.map((step, index) => { const label = `authorization.steps[${index}]`; object(step, label); exactKeys(step, label, ["action", "requiredChecks", "stepId"]); safeIdentifier(step.stepId, `${label}.stepId`); if (!config.allowedActions.includes(step.action)) throw new Error(`${label}.action is not policy-authorized`); if (!Array.isArray(step.requiredChecks) || !sameArray(step.requiredChecks, REQUIRED_ACTION_CHECKS[step.action])) throw new Error(`${label}.requiredChecks must be exact for ${step.action}`); return step.action; });
  if (new Set(bundle.steps.map((step) => step.stepId)).size !== bundle.steps.length) throw new Error("authorization stepIds must be unique"); const first = GROUPED_AUTHORIZATION_ACTIONS.indexOf(actions[0]); if (first < 0 || !sameArray(actions, GROUPED_AUTHORIZATION_ACTIONS.slice(first, first + actions.length))) throw new Error("authorization steps must be one contiguous delivery sequence"); if (candidate.commitSha === null && actions[0] !== "commit_candidate") throw new Error("a candidate without commitSha must begin with commit_candidate"); if (candidate.commitSha !== null && actions.includes("commit_candidate")) throw new Error("an already committed candidate cannot authorize another commit"); return structuredClone(bundle);
}
